version: '3.9'
networks:
  dem:
services:
  db:
    image: postgres_image_dbtarget
    command: postgres -c datestyle='iso, dmy'
    build: ./motor_aposta/infrastructure/database/
    restart: always
    environment:
      POSTGRES_DB: dbTarget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F4milia_2023_
    volumes:
      - /motor_aposta/infrastructure/database/dbTarget.sql /docker-entrypoint-initdb.d/
    ports:
      - "7543:5432"
    networks:
      - dem
  web:
    build: .
    command: uvicorn motor_aposta.api.controller.view_aposta:app --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_DB: dbTarget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F4milia_2023_
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dem
